[build]  
  command = "cd types && npm install --legacy-peer-deps && cd ../client && npm install --legacy-peer-deps && npm run build"
  publish = "client/dist"

# Rule for router history mode
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
