version: 2
services:
  metadesk-server:
    source:
      directory: server
    build:
      commands:
        - npm install
        - npm run build
    start:
      command: npm start
    variables:
      NODE_ENV: production
      PORT: ${{ PORT }}
    domains:
      - metadesk-dev.up.railway.app