services:
  - type: web
    name: metadesk-server
    runtime: node
    region: oregon
    plan: free
    buildCommand: yarn install && cd server && yarn install && cd .. && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
      - key: HOST
        value: 0.0.0.0
