services:
  - type: web
    name: metadesk-server
    runtime: node
    region: oregon
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
      - key: HOST
        value: 0.0.0.0
